export const rawKoreanUniversities = [
    { "ru": "Сеульский национальный университет", "ko": "서울대학교", "en": "Seoul National University" },
    { "ru": "Университет Корё", "ko": "고려대학교", "en": "Korea University" },
    { "ru": "Университет Ёнсе", "ko": "연세대학교", "en": "Yonsei University" },
    { "ru": "Университет Сонгюнгван", "ko": "성균관대학교", "en": "Sungkyunkwan University" },
    { "ru": "Университет Ханьян", "ko": "한양대학교", "en": "Hanyang University" },
    { "ru": "Университет Соган", "ko": "서강대학교", "en": "Sogang University" },
    { "ru": "Университет Чунан", "ko": "중앙대학교", "en": "Chung-Ang University" },
    { "ru": "Университет Кёнхи", "ko": "경희대학교", "en": "Kyung Hee University" },
    { "ru": "Университет иностранных языков Хангук", "ko": "한국외국어대학교", "en": "Hankuk University of Foreign Studies" },
    { "ru": "Университет Сеула", "ko": "서울시립대학교", "en": "University of Seoul" },
    { "ru": "Университет Конкук", "ko": "건국대학교", "en": "Konkuk University" },
    { "ru": "Университет Тонгук", "ko": "동국대학교", "en": "Dongguk University" },
    { "ru": "Университет Хонъик", "ko": "홍익대학교", "en": "Hongik University" },
    { "ru": "Университет Кукмин", "ko": "국민대학교", "en": "Kookmin University" },
    { "ru": "Университет Сунсиль", "ko": "숭실대학교", "en": "Soongsil University" },
    { "ru": "Университет Седжон", "ko": "세종대학교", "en": "Sejong University" },
    { "ru": "Университет Тангук", "ko": "단국대학교", "en": "Dankook University" },
    { "ru": "Университет Мёнджи", "ko": "명지대학교", "en": "Myongji University" },
    { "ru": "Университет Санмён", "ko": "상명대학교", "en": "Sangmyung University" },
    { "ru": "Университет Кванвун", "ko": "광운대학교", "en": "Kwangwoon University" },
    { "ru": "Университет Согён", "ko": "서경대학교", "en": "Seokyeong University" },
    { "ru": "Университет Самюк", "ko": "삼육대학교", "en": "Sahmyook University" },
    { "ru": "Университет Хансон", "ko": "한성대학교", "en": "Hansung University" },
    { "ru": "Сеульский национальный университет науки и технологий", "ko": "서울과학기술대학교", "en": "Seoul National University of Science and Technology" },
    { "ru": "Женский университет Ихва", "ko": "이화여자대학교", "en": "Ewha Womans University" },
    { "ru": "Женский университет Сукмян", "ko": "숙명여자대학교", "en": "Sookmyung Women's University" },
    { "ru": "Женский университет Сонсин", "ko": "성신여자대학교", "en": "Sungshin Women's University" },
    { "ru": "Сеульский женский университет", "ko": "서울여자대학교", "en": "Seoul Women's University" },
    { "ru": "Женский университет Тондок", "ko": "동덕여자대학교", "en": "Dongduk Women's University" },
    { "ru": "Женский университет Токсон", "ko": "덕성여자대학교", "en": "Duksung Women's University" },
    { "ru": "КАИСТ", "ko": "한국과학기술원", "en": "KAIST" },
    { "ru": "ПОСТЕК", "ko": "포항공과대학교", "en": "POSTECH" },
    { "ru": "ГИСТ", "ko": "광주과학기술원", "en": "GIST" },
    { "ru": "ДГИСТ", "ko": "대구경북과학기술원", "en": "DGIST" },
    { "ru": "ЮНИСТ", "ko": "울산과학기술원", "en": "UNIST" },
    { "ru": "Корейский национальный университет искусств", "ko": "한국예술종합학교", "en": "Korea National University of Arts" },
    { "ru": "Корейский национальный спортивный университет", "ko": "한국체육대학교", "en": "Korea National Sport University" },
{ "ru": "Корейский национальный педагогический университет", "ko": "한국교원대학교", "en": "Korea National University of Education" },
    { "ru": "Корейский технологический университет", "ko": "한국공학대학교", "en": "Tech University of Korea" },
    { "ru": "Корейский аэрокосмический университет", "ko": "한국항공대학교", "en": "Korea Aerospace University" },
    { "ru": "Корейский морской и океанический университет", "ko": "한국해양대학교", "en": "Korea Maritime & Ocean University" },
    { "ru": "Университет Инха", "ko": "인하대학교", "en": "Inha University" },
    { "ru": "Инчхонский национальный университет", "ko": "인천대학교", "en": "Incheon National University" },
    { "ru": "Университет Аджу", "ko": "아주대학교", "en": "Ajou University" },
    { "ru": "Университет Качхон", "ko": "가천대학교", "en": "Gachon University" },
    { "ru": "Университет Кёнги", "ko": "경기대학교", "en": "Kyonggi University" },
    { "ru": "Католический университет Кореи", "ko": "가톨릭대학교", "en": "The Catholic University of Korea" },
    { "ru": "Университет Чха", "ko": "차의과학대학교", "en": "CHA University" },
    { "ru": "Ханкёнский национальный университет", "ko": "한경국립대학교", "en": "Hankyong National University" },
    { "ru": "Университет Тэджин", "ko": "대진대학교", "en": "Daejin University" },
    { "ru": "Пхёнтхэкский университет", "ko": "평택대학교", "en": "Pyeongtaek University" },
    { "ru": "Университет Сонгёль", "ko": "성결대학교", "en": "Sungkyul University" },
    { "ru": "Университет Аньян", "ko": "안양대학교", "en": "Anyang University" },
    { "ru": "Университет Синхан", "ko": "신한대학교", "en": "Shinhan University" },
    { "ru": "Университет Хёпсон", "ko": "협성대학교", "en": "Hyupsung University" },
    { "ru": "Университет Каннам", "ko": "강남대학교", "en": "Kangnam University" },
    { "ru": "Университет Йонъин", "ko": "용인대학교", "en": "Yong In University" },
    { "ru": "Университет Сувон", "ko": "수원대학교", "en": "The University of Suwon" },
    { "ru": "Университет Ыльджи", "ko": "을지대학교", "en": "Eulji University" },
    { "ru": "Канвонский национальный университет", "ko": "강원대학교", "en": "Kangwon National University" },
    { "ru": "Национальный университет Каннын-Вонджу", "ko": "국립강릉원주대학교", "en": "Gangneung-Wonju National University" },
    { "ru": "Университет Халлим", "ko": "한림대학교", "en": "Hallym University" },
    { "ru": "Католический университет Квандон", "ko": "가톨릭관동대학교", "en": "Catholic Kwandong University" },
    { "ru": "Университет Санджи", "ko": "상지대학교", "en": "Sangji University" },
    { "ru": "Чуннамский национальный университет", "ko": "충남대학교", "en": "Chungnam National University" },
    { "ru": "Чунбукский национальный университет", "ko": "충북대학교", "en": "Chungbuk National University" },
    { "ru": "Ханбатский национальный университет", "ko": "국립한밭대학교", "en": "Hanbat National University" },
    { "ru": "Университет Ханнам", "ko": "한남대학교", "en": "Hannam University" },
    { "ru": "Университет Моквон", "ko": "목원대학교", "en": "Mokwon University" },
    { "ru": "Университет Пэджэ", "ko": "배재대학교", "en": "Pai Chai University" },
    { "ru": "Университет Усон", "ko": "우송대학교", "en": "Woosong University" },
    { "ru": "Тэджонский университет", "ko": "대전대학교", "en": "Daejeon University" },
    { "ru": "Университет Сунчхонхян", "ko": "순천향대학교", "en": "Soonchunhyang University" },
    { "ru": "Университет Хосо", "ko": "호서대학교", "en": "Hoseo University" },
    { "ru": "Университет Сонмун", "ko": "선문대학교", "en": "Sun Moon University" },
    { "ru": "Намсеульский университет", "ko": "남서울대학교", "en": "Namseoul University" },
    { "ru": "Корейский университет технологий и образования", "ko": "한국기술교육대학교", "en": "KOREATECH" },
    { "ru": "Конджунский национальный университет", "ko": "국립공주대학교", "en": "Kongju National University" },
    { "ru": "Университет Чхонджу", "ko": "청주대학교", "en": "Cheongju University" },
    { "ru": "Университет Совон", "ko": "서원대학교", "en": "Seowon University" },
{ "ru": "Университет Семён", "ko": "세명대학교", "en": "Semyung University" },
    { "ru": "Корейский национальный транспортный университет", "ko": "국립한국교통대학교", "en": "Korea National Transportation University" },
    { "ru": "Кёнбукский национальный университет", "ko": "경북대학교", "en": "Kyungpook National University" },
    { "ru": "Университет Йоннам", "ko": "영남대학교", "en": "Yeungnam University" },
    { "ru": "Университет Кемен", "ko": "계명대학교", "en": "Keimyung University" },
    { "ru": "Тэгуский католический университет", "ko": "대구가톨릭대학교", "en": "Daegu Catholic University" },
    { "ru": "Тэгуский университет", "ko": "대구대학교", "en": "Daegu University" },
    { "ru": "Глобальный университет Хандон", "ko": "한동대학교", "en": "Handong Global University" },
    { "ru": "Кымоский национальный технологический институт", "ko": "국립금오공과대학교", "en": "Kumoh National Institute of Technology" },
    { "ru": "Андонский национальный университет", "ko": "국립안동대학교", "en": "National Andong University" },
    { "ru": "Пусанский национальный университет", "ko": "부산대학교", "en": "Pusan National University" },
    { "ru": "Пукёнский национальный университет", "ko": "국립부경대학교", "en": "Pukyong National University" },
    { "ru": "Университет Тонъа", "ko": "동아대학교", "en": "Dong-A University" },
    { "ru": "Университет Кёнсон", "ko": "경성대학교", "en": "Kyungsung University" },
    { "ru": "Университет Тонсо", "ko": "동서대학교", "en": "Dongseo University" },
    { "ru": "Университет Тоный", "ko": "동의대학교", "en": "Dong-Eui University" },
    { "ru": "Университет Силла", "ko": "신라대학교", "en": "Silla University" },
    { "ru": "Пусанский университет иностранных языков", "ko": "부산외국어대학교", "en": "Busan University of Foreign Studies" },
    { "ru": "Ульсанский университет", "ko": "울산대학교", "en": "University of Ulsan" },
    { "ru": "Кёнсанский национальный университет", "ko": "경상국립대학교", "en": "Gyeongsang National University" },
    { "ru": "Чханвонский национальный университет", "ko": "국립창원대학교", "en": "Changwon National University" },
    { "ru": "Университет Индже", "ko": "인제대학교", "en": "Inje University" },
    { "ru": "Кённамский университет", "ko": "경남대학교", "en": "Kyungnam University" },
    { "ru": "Чоннамский национальный университет", "ko": "전남대학교", "en": "Chonnam National University" },
    { "ru": "Чонбукский национальный университет", "ko": "전북대학교", "en": "Jeonbuk National University" },
    { "ru": "Университет Чосон", "ko": "조선대학교", "en": "Chosun University" },
    { "ru": "Университет Хонам", "ko": "호남대학교", "en": "Honam University" },
    { "ru": "Университет Кванджу", "ko": "광주대학교", "en": "Gwangju University" },
    { "ru": "Мокпхоский национальный университет", "ko": "국립목포대학교", "en": "Mokpo National University" },
    { "ru": "Сунчхонский национальный университет", "ko": "국립순천대학교", "en": "Sunchon National University" },
    { "ru": "Университет Вонкванг", "ko": "원광대학교", "en": "Wonkwang University" },
    { "ru": "Университет Чонджу", "ko": "전주대학교", "en": "Jeonju University" },
    { "ru": "Кунсанский национальный университет", "ko": "국립군산대학교", "en": "Kunsan National University" },
    { "ru": "Университет Усок", "ko": "우석대학교", "en": "Woosuk University" },
    { "ru": "Чеджуский национальный университет", "ko": "제주대학교", "en": "Jeju National University" }
  ]